### ISSUE TITLE
论文的图有个小错误

### ISSUE THREAD

**Issue by menghuaa** [zhaoyuzhi/SVCNet#2]
Fig. 1. Illustration of the data flows of (a) SVCNet (including CPNet and SSNet)
<img width="127" alt="image" src="https://github.com/zhaoyuzhi/SVCNet/assets/48876313/4504c6fa-d3db-44e4-aa5d-d70fdedb36ff">
yi+3,图里是yt+3

**Comment by menghuaa** [comment]
您好，您论文中使用的Correspondence Module是否就是deep exemplar-based video colorization这篇论文中的Correspondence Module？我看您的代码，应该是直接使用了deep exemplar-based video colorization提供的权重vgg19_conv.pth、nonlocal_net_iter_76000.pth，但是论文中似乎只提及了使用预训练权重vgg19_conv.pth，而没提到使用nonlocal_net_iter_76000.pth

**Comment by zhaoyuzhi** [comment]
感谢指出，下次revision会改过来

**Comment by menghuaa** [comment]
> 感谢指出，下次修订会改过来

你好，还有我看到你论文中loss部分
<img width="172" alt="image" src="https://github.com/zhaoyuzhi/SVCNet/assets/48876313/70d830f6-f7bf-40c0-a64d-2be89cf9bae3">
<img width="267" alt="image" src="https://github.com/zhaoyuzhi/SVCNet/assets/48876313/7dac0f73-3fa3-4f9f-9d42-46e62d2df6da">
有gt是下采样的，但是我看代码您这些模块的输出都是和gt同分辨率的，只是超分那部分的gt是上采样的，想确认一下是您论文写错了还是我看错了

**Comment by zhaoyuzhi** [comment]
哪个式子写错了？只有sr部分会返回原始分辨率

**Comment by menghuaa** [comment]
> 哪个式子写错了？只有sr部分会返回原始分辨率

我又看了一下论文，您没有写错，但是感觉有点奇怪。您输入256*448的图片，但是将512*896作为原始分辨率，这个512*896的图片还是通过resize获得的。正常来讲不应该，输入256*448的图片，没有sr前输出128*224的图片，sr后输出256*448的图片吗？

**Comment by zhaoyuzhi** [comment]
Hi 解释如下：
1. 大部分操作固定在了256分辨率(256x448)，是为了节省计算资源。比如输入是4k的视频，考虑到颜色通道（color embedding）比较稀疏，即先在256分辨率做上色，再super resolution还原回原始输入的分辨率，sr这一步基本不会导致最终输出的blur，因为只涉及两个颜色通道
i.e., 上色都固定在256分辨率上做，sr只是为了还原原始分辨率
2. 如果把大部分操作固定在128分辨率，文章有做ablation study，TABLE III的setting 7)，效果会差很多。固定在256分辨率是实验出来的效果-计算资源消耗的trade-off
3. 训练时将最终输出resize到512分辨率是因为训练集GT图像不是这个分辨率，但是和512分辨率非常接近（比如480x832），就直接用了resize，并不会有明显的blur现象

**Comment by menghuaa** [comment]
> Hi 解释如下：
> 
> 1. 大部分操作固定在了256分辨率(256x448)，是为了节省计算资源。比如输入是4k的视频，考虑到颜色通道（color embedding）比较稀疏，即先在256分辨率做上色，再super resolution还原回原始输入的分辨率，sr这一步基本不会导致最终输出的blur，因为只涉及两个颜色通道
>    i.e., 上色都固定在256分辨率上做，sr只是为了还原原始分辨率
> 2. 如果把大部分操作固定在128分辨率，文章有做ablation study，TABLE III的setting 7)，效果会差很多。固定在256分辨率是实验出来的效果-计算资源消耗的trade-off
> 3. 训练时将最终输出resize到512分辨率是因为训练集GT图像不是这个分辨率，但是和512分辨率非常接近（比如480x832），就直接用了resize，并不会有明显的blur现象

2是不是可以理解为输入128分辨率效果变差，回到原图需要超分4倍，缺失的细节更多，超分效果不好

**Comment by zhaoyuzhi** [comment]
你好，可以理解是128分辨率的上色效果变差。如果固定在128分辨率做上色，图像的细节很可能挤在一起，上色效果就不好

其实超分在这个模型里面不太重要，可以简单试试把RGB图像转换为Lab通道，对ab两个通道下采样再上采样4倍，最后转换回RGB，会发现其实和原来的图像基本没区别
